# Generated by Django 2.0 on 2020-06-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlackListApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='date',
            field=models.CharField(default='', max_length=12),
        ),
    ]
