# Generated by Django 2.0 on 2020-06-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactFormApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformapp',
            name='date',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='contactformapp',
            name='time',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='contactformapp',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
