# Generated by Django 2.0 on 2020-05-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarapp', '0003_auto_20200527_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycar',
            name='fb',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='mycar',
            name='tw',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='mycar',
            name='yt',
            field=models.TextField(default='-'),
        ),
    ]
