# Generated by Django 2.0 on 2020-05-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarapp', '0004_auto_20200527_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycar',
            name='set_name',
            field=models.TextField(default='-'),
        ),
    ]
