# Generated by Django 2.0 on 2020-05-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarapp', '0005_mycar_set_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycar',
            name='link',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='mycar',
            name='tell',
            field=models.TextField(default='-'),
        ),
    ]
