# Generated by Django 2.0 on 2020-05-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycarapp', '0006_auto_20200527_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycar',
            old_name='link',
            new_name='Link',
        ),
        migrations.RenameField(
            model_name='mycar',
            old_name='tell',
            new_name='Tell',
        ),
    ]
