# Generated by Django 2.0 on 2020-05-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarapp', '0007_auto_20200527_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycar',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
