# Generated by Django 2.0 on 2020-05-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarapp', '0008_auto_20200527_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycar',
            name='Link',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='mycar',
            name='Tell',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='mycar',
            name='fb',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='mycar',
            name='set_name',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='mycar',
            name='tw',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='mycar',
            name='yt',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
