# Generated by Django 2.0 on 2020-06-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarapp', '0009_auto_20200527_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycar',
            name='picname',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mycar',
            name='picurl',
            field=models.TextField(default=''),
        ),
    ]
