# Generated by Django 2.0 on 2020-06-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarapp', '0011_auto_20200611_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycar',
            name='abouttxt',
            field=models.TextField(default=''),
        ),
    ]
