# Generated by Django 2.0 on 2020-06-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarapp', '0012_mycar_abouttxt'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycar',
            name='seo_keyword',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='mycar',
            name='seo_txt',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
