# Generated by Django 2.0 on 2020-06-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerapp',
            name='email',
            field=models.CharField(default='', max_length=30),
        ),
    ]
