# Generated by Django 2.0 on 2020-06-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0002_managerapp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerapp',
            name='age',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='managerapp',
            name='lastname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='managerapp',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='managerapp',
            name='usertxt',
            field=models.CharField(default='', max_length=30),
        ),
    ]
