# Generated by Django 2.0 on 2020-06-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0003_auto_20200616_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerapp',
            name='age',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='managerapp',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='managerapp',
            name='lastname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='managerapp',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='managerapp',
            name='usertxt',
            field=models.TextField(),
        ),
    ]
