# Generated by Django 2.0 on 2020-06-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0004_auto_20200620_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerapp',
            name='age',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='managerapp',
            name='email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='managerapp',
            name='lastname',
            field=models.TextField(),
        ),
    ]
