# Generated by Django 2.0 on 2020-06-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0006_auto_20200620_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerapp',
            name='ip',
            field=models.TextField(default=''),
        ),
    ]
