# Generated by Django 2.0 on 2020-06-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0007_managerapp_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerapp',
            name='country',
            field=models.TextField(default=''),
        ),
    ]
