# Generated by Django 2.0 on 2020-06-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CategoryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryapp',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
