# Generated by Django 2.0 on 2020-06-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestapp', '0003_auto_20200602_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggest',
            name='time',
            field=models.CharField(default='00:00', max_length=12),
        ),
    ]
