# Generated by Django 2.0 on 2020-06-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestapp', '0004_suggest_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggest',
            name='or_catid',
            field=models.IntegerField(default=0),
        ),
    ]
