# Generated by Django 2.0 on 2020-06-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestapp', '0005_suggest_or_catid'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggest',
            name='tag',
            field=models.TextField(default=''),
        ),
    ]
