# Generated by Django 2.0 on 2020-06-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestapp', '0006_suggest_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggest',
            name='act',
            field=models.IntegerField(default=0),
        ),
    ]
