# Generated by Django 2.0 on 2020-06-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestapp', '0007_suggest_act'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggest',
            name='rand',
            field=models.IntegerField(default=0),
        ),
    ]
