# Generated by Django 2.0 on 2020-06-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestapp', '0008_suggest_rand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggest',
            name='rand',
        ),
    ]
