# Generated by Django 2.0 on 2020-06-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestapp', '0010_suggest_rand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggest',
            name='rand',
            field=models.BigIntegerField(default=0),
        ),
    ]
